config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = if params[:search]
                Tweet.where("username LIKE ?", "%#{params[:search]}%")
              else
                Tweet.all
              end.paginate(page: params[:page], per_page: 10)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "El Tweet fúe creado satisfactoriamente." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "El Tweet fúe actualizado satisfactoriamente." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "El Tweet fúe eliminado satisfactoriamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :username, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAppTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container d-flex flex-column justify-content-center col-4 gap-2">
    <%= yield %>
  <div>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: tweet) do |form| %>
      <% if tweet.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

          <ul>
            <% tweet.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mb-2">
        <%= form.label :username, style: "display: block" %>
        <%= form.text_field :username, class: "form-control" %>
      </div>

      <div class="form-group mb-2">
        <%= form.label :description, style: "display: block" %>
        <%= form.text_field :description, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= form.label :profile, style: "display: block" %>

        <% if action_name == 'edit' %>
        <%= image_tag tweet.profile, width: 50, height: 50, alt: "Profile Image" %>
        <% end %>
        
        <% if action_name == 'new' %>
        <% fake_profile = Faker::Avatar.image %>
        <img src="<%= fake_profile %>" width="50" height="50" alt="Profile Image" />
         <%= form.hidden_field :profile, value: fake_profile %>
        <% end %>



      </div>

      <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>" class="card mb-2">
  <div class="card-body">
    <h5 class="card-title">Perfil</h5>
      <div class="d-flex flex-row gap-3 mb-2">
      <%= image_tag tweet.profile, width: 50, height: 50, alt: "Profile Image" %>
      <div class="align-self-center">
        <p class="card-text">
          <strong>Nombre de usuario:</strong>
          <%= tweet.username %>
        </p>
        <p class="card-text m-0">
          <strong>Descripción:</strong>
        </p>
        <p class="card-text">
      <%= tweet.description %>
      </div>
      </div>
    </p>
    <%# valida que se oculte el boton cuando esta en la ruta show %>
    <% unless action_name == 'show' %>
    
    <div class="d-flex justify-content-end">
      <%= link_to "Mostrar Tweet", tweet, class: "btn btn-primary mr-2" %>
      <%= button_to "Eliminar", tweet_path(id), method: :delete, class: "btn btn-danger" %> 
    </div>
    
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editar tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Mostrar", @tweet %> |
  <%= link_to "Volver", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mb-4">Twitter</h1>
<%= link_to "Nuevo Tweet", new_tweet_path, class: "btn btn-info mb-2" %>

<%= form_with(url: tweets_path, method: :get, class: "mb-4 d-flex") do |form| %>

    <%= form.text_field :search, placeholder: "Buscar tweets", class: "form-control mr-1" %>
    <%= form.submit "Buscar", class: "btn btn-primary mr-1" %>
    <%= link_to "Limpiar", tweets_path, class: "btn btn-secondary", data: { turbolinks: false } %>

<% end %>

<div id="tweets">
  <% @tweets.each do |tweet| %>
     <%= render partial: 'tweet', locals: { tweet: tweet, id: tweet.id } %>
  <% end %>
</div>


<nav>
  <ul class="pagination">
    <%= paginate @tweets %>
  </ul>
</nav>

app/views/tweets/new.html.erb
<h1>Crear Tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Volver", tweets_path, class: "btn btn-secondary" %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Volver", tweets_path, class: "btn btn-secondary" %>
  <%= link_to "Editar", edit_tweet_path(@tweet), class: "btn btn-primary" %>
</div>